<?php

?>
<h1>Lista de Pessoas </h1>
<table class="table table-stripped">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Situação</th>
    </tr>
    <?php

    foreach ($pessoas as $pes) :
        ?>
    <tr>
        <td><?= $pes->getId() ?></td>
        <td><?= $pes->getNome() ?> <?= $pes->getSobrenome() ?></td>
        <td><?= $pes->getEmail() ?></td>
        <td><?= $pes->getSituacao() ?></td>
    </tr>

    <?php
endforeach;



?>
</table>